### ISSUE TITLE
Can you push latest release to Hex?

### ISSUE THREAD

**Issue by epilgrim** [findmypast/vaultex#38]
Latest release in Hex is 12.0, which is not compatible with Poison 4.
Version 12.3 is

Thank you!!!

**Comment by 03k64** [comment]
Hello, thanks for raising this issue. Our internal CI pipeline was misbehaving. We've now fixed the issue and bumped to v12.4 in order to fix publishing of documentation also. Let us know if you have any issues with the new version and we can either re-open or open a new issue as appropriate. Thanks.
